id: P009564
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:38:19.044826
source_metadata:
  id: bdr:W8LS17977
  title: ཆོས་སྡེ་བཀྲ་ཤིས་དགེ་འཕེལ་གྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    4949d6b7e8b4499186652cf6ed89ef60:
      image_group_id: I8LS17988
      title: ''
      volume_number: 1
      total_pages: 82
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
