id: P009564
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17977
  title: ཆོས་སྡེ་བཀྲ་ཤིས་དགེ་འཕེལ་གྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    4949d6b7e8b4499186652cf6ed89ef60:
      image_group_id: I8LS17988
      title: ''
      volume_number: 1
      total_pages: 82
